<!-- Auto-generated by Markscribe. DO NOT EDIT README.md DIRECTLY -->

<div align="center">
  <a href="https://in.linkedin.com/in/md-irfan-raj">
    <img src="https://img.shields.io/badge/LinkedIn-Connect-blue?style=for-the-badge&logo=linkedin" />
  </a>
</div>

---

<h1 align="center">👋 Hi, I'm MD IRFAN RAJ</h1>
<h3 align="center">💻 Software Developer | 🌐 AI & Full-Stack Enthusiast</h3>
<h4 align="center">🎓 IIIT Bhagalpur | 🚀 Seeking Software Engineering Internship</h4>

---

<p align="center">
  <img src="https://komarev.com/ghpvc/?username=MD-IRFAN-RAJ&label=Profile%20Views&color=0e75b6&style=flat" />
</p>

---

## 🚀 About Me

- 💡 Innovation-driven developer building scalable solutions  
- 🌱 Exploring **AI, System Design, Microservices**  
- 🔭 Lead Developer – **Swasthya Sampark (Healthcare Platform)**  
- ⚡ Full-Stack • Cloud • AI  
- 📫 Email: **mdirfanraj88.omega@gmail.com**  
- 🌐 Portfolio: https://md-irfan-raj.github.io/PortFolio  

---

## 🛠️ Technical Stack

**Frontend**  
React, Next.js, Redux, HTML, CSS, JavaScript, TypeScript, Tailwind  

**Backend & Cloud**  
Node.js, Express, MongoDB, PostgreSQL, AWS, GCP, Azure  

---

## 🌟 Featured Projects

### 🏥 Swasthya Sampark
- MERN, WebRTC, Socket.io
- Telemedicine & Emergency Alerts
- Status: 🚧 In Development

### 🤖 AI README Generator
- Next.js, AI APIs
- https://aireadmegenerator.vercel.app
- Status: ✅ Live

### 📰 AI News Platform
- React, Node.js, AI
- https://ey-news-app-display.onrender.com
- Status: ✅ Deployed

---

## ⏱️ Coding Activity (Hackatime)

### 💾 Languages
{{ wakatimeData.Languages | wakatimeCategoryBar 5 }}

### 💼 Projects
{{ wakatimeData.Projects | wakatimeCategoryBar 5 }}

---

## 📊 GitHub Analytics

<p align="center">
  <img src="https://github-readme-stats.vercel.app/api?username=MD-IRFAN-RAJ&show_icons=true&theme=tokyonight" height="160"/>
  <img src="https://github-readme-stats.vercel.app/api/top-langs/?username=MD-IRFAN-RAJ&layout=compact&theme=tokyonight" height="160"/>
</p>

---

## 🔥 Contribution Streak

<p align="center">
  <img src="https://github-readme-streak-stats.herokuapp.com/?user=MD-IRFAN-RAJ&theme=tokyonight&hide_border=true"/>
</p>

---

## 🌱 Contribution Graph

<p align="center">
  <img src="https://github-readme-activity-graph.vercel.app/graph?username=MD-IRFAN-RAJ&theme=react-dark&area=true"/>
</p>

---

## 🤝 Connect With Me

<p align="center">
  <a href="https://www.linkedin.com/in/md-irfan-raj">
    <img src="https://img.shields.io/badge/LinkedIn-0A66C2?logo=linkedin&style=for-the-badge"/>
  </a>
  <a href="https://leetcode.com/u/real_Buraq/">
    <img src="https://img.shields.io/badge/LeetCode-FFA116?logo=leetcode&style=for-the-badge"/>
  </a>
  <a href="https://www.credly.com/users/md-irfan-raj/badges">
    <img src="https://img.shields.io/badge/Credly-FF6B35?logo=credly&style=for-the-badge"/>
  </a>
</p>

---

⭐ _This README is auto-generated using **Markscribe**_
